BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040

VIA_ENABLE = yes
LTO_ENABLE = no

I2C_DRIVER_REQUIRED = no
SPI_DRIVER_REQUIRED = no
UART_DRIVER_REQUIRED = no
WS2812_DRIVER_REQUIRED = no

CONSOLE_ENABLE = no
DEBUG_ENABLE = no